apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-scheduling-quartz-posgres-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-scheduling-quartz-postgres
  template:
    metadata:
      labels:
        app: demo-scheduling-quartz-postgres
    spec:
      containers:
        - name: demo-scheduling-quartz-postgres
          image: demo-scheduling-quartz-postgres:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          env:
            - name: POSTGRES_SERVICE
              value: postgres-quartz-service
            - name: POSTGRES_USER
              value: quartz
            - name: POSTGRES_PASSWORD
              value: "12345678"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-scheduling-quartz-postgres-service
spec:
  selector:
    app: demo-scheduling-quartz-postgres
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
